global using Application.Data.DataBaseContext;
global using Application.Dtos;
global using Application.Exceptions;
global using Application.Mapper;
global using AutoMapper;
global using Domain.Model;
global using Domain.ValueObjects;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Logging;
